name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.0.7

    steps:
    - uses: actions/checkout@v2
    - name: Fetch Deps
      run: make get_deps
    - name: Ensure elvis is installed
      run: make ensure_elvis
    - name: Compile
      run: make compile
    - name: Run Xref
      run: make xref
    - name: Run Dialyzer
      run: make dialyze
    - name: Run erlfmt
      run: make check_format
    - name: Run linter
      run: make lint
    - name: Run tests (eunit, proper)
      run: make test
