name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.0.7

    steps:
    - uses: actions/checkout@v2
    - name: Cache rebar
      if: ${{ !env.ACT }}
      uses: actions/cache@v2
      with:
        path: "~/.cache/rebar3"
        key: ${{ runner.os }}-${{ hashFiles('rebar.lock') }}-rebar
    - name: Cache build
      if: ${{ !env.ACT }}
      id: cache-build
      uses: actions/cache@v2
      with:
        path: "_build"
        key: ${{ runner.os }}-${{ hashFiles('rebar.lock') }}-build
    - name: Fetch Deps
      run: make get_deps
    - name: Compile
      run: make compile
    - name: Run Xref
      run: make xref
    - name: Run Dialyzer
      run: make dialyze
    - name: Run erlfmt
      run: make check_format
    - name: Run linter
      run: make lint
    - name: Run tests (eunit, proper)
      run: make test
